{% set version = "0.3-4" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-nls2
  version: {{ version|replace("-", "_") }}

source:
  fn: nls2_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/nls2_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/nls2/nls2_{{ version }}.tar.gz
  sha256: c8a6f7fd12b50aa6eeb2b565f94de7aaaa59aa18eabc72c4185124a1b4399297

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-proto

  run:
    - r-base
    - r-proto

test:
  commands:
    - $R -e "library('nls2')"  # [not win]
    - "\"%R%\" -e \"library('nls2')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/nls2/index.html
  license: GPL-2
  summary: Adds brute force and multiple starting values to nls.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
