travis:
  secure:
    BINSTAR_TOKEN: jHmcRgwrUO8h/X71h2AoyOCFB790YUIt1kokmkKszNx/Z5VxNo1uUSbEFltrFuNt2csHMURt0zTQFMUgRs9ft3wry/0lWzwGmTvwH7CLO5HhtzThOMhBia+Wi8i3o2kIBZduf3OMlxOvQmL08f5LJlO9ZskYev2AB9t0LWtLnHJSdbxUe/acqE0fnK+1J4Yb0XjmiOeT8AVqAFMa52sJHZPzH8+wL3sZiaMIreDQmQ+xx1RrulkwrhOFSITKwm6RZhl3sLFMKNFNJW7snJqzIWfAmFqdB1d8OsAER/NW5LnX2ZwO1AX2upTq2DjXYfinGKpfTtl4vPNorqyQ88KrCRgGDF3PT1yDbVcJEqUAOZdnh1oL2vEbLR6byZVf5rj+/1BU18+Kt6Iy4EGM/Lgr17iax0wnAQF99F55KxMLypHRWsVsnnUa2izoskSzJH9fUMdEXfiHYZKHlj/X8eLuL9yUrnzvMPGsDBsFLNJ/xPuaO4S/fuZoX1hCQzrVBVxDW9FFlL8qI+uGgegJsfQcX4A8xUkJ4EvWvZrGc3bWhSlp4PYwYP+H8dg4W5iEW2OVEWhsPIy+7c+aYv+CFSdSfh/z0uPP9tfX3ajK4HWP+Po071Zo2/zPiTMKKjaaXHAeTp5FFRHLBZU8vrxSYS8JcSnQFliMR0mZFuApGFw0KkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
