travis:
  secure:
    BINSTAR_TOKEN: VhR4o+0Er7+qURaiDI3uI11alW+tQ3zXFGUFM9t9+POFD/7htz2dDwwl07i9hrAxAZ+rDpi4yvlIrTVC8/XTP+8RfGk6DsEAA707pUbt+/SJvDUx+FOv0+MLOhyrkexzsXLenf4cQXepAqMfLCsE4noNyoNJhs7XbWdA/UEodq7BpmvuVTX5zeMA7OTaYSaQSV3gdoIt8F9Zk9Ym6qo2v5IFEdRGK8xJuAbKwfD2LUXEvdC2urUbftXlQhOnE2g4c3Tlg+2MHBZ0wF++v8+aLsTJbABQheOmd8k2u0YbOW9iMNZIdeQ5ACIrG/rqU3JcFMXuF6WaoMYdxkegrUFT011iXYcWbWeI3tMUUkvDLicDYgzx5/2p+OnO3ME0v9nwqFvJbjomZUExJ+H4d42s1NkOQNR+KEbnz1sriYKEWpR+0vPSFeMKttbRnnC+9Brv1B3c4286HfJLcxf8lLNjomlcLHnCAyoxqmnb5XW/9HlriAMQaqNdueofzd/M/LJIqOe85jEEiIW/1J2+6GgHEcx9ueW45clH7aR/oIULhR9H7rlPbH4OIQXUMJCFmK2q3gJKFTuJ0qx5mVdn7oQnnYGZzXJC1Io/5iiX1CcodtA1Nm1WKot+yytyQGkq05jl49QaPevoJjK3QaQRQyoUg/CvGCumu1HMkHSm0zMERQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
