travis:
  secure:
    BINSTAR_TOKEN: PNgI26JJVViCyQd8Gkl2D1bP3Z95Te1iUCyd925Q6c31LoBvLOMC/AtfQpHu4w7ntk9xNMDvrcvGxNdsN3KgIw9yCDr7zF2NmgkGj2sgDNtysXZq5jIfG1Mb76wCnJkxgTbVZU9qIqqZCP4ZjIaD3SYkKvfjAyz2YpjESV22temUFqhuzNLpTvGNYsE1WCO+sJrLDdkUge939bSUK+uv1ggxYDMkt/FaZd0nK7+hB0OPanoooDiBVjEe27pgrt6HXxdjZbZYbYxeaqYukMJkDz5ZKWst3pzdw2YVlTFwxy2h2qvO7vrkkLRg7RHqU7HLtYtGhrh4a3tGzMxhIT/ak1o6rV1k5MCBK32YpkVsSu6yHnbVJWGyJY4h326Pk+2IW4wprPez5Rmh9KlfEhUggI2/FXVtQZFle7lxp77FgKRoJeUa3yy/AVkrt1pCMGqYb2QZe50f7RZY06iZQ4xFzTl4Ajq08bb3T+IJ26j0ae2ii0i9BBvrLrZnHFuL7Ph+dSuQqT0eOsmEag/rwrBmPQk1dQqLkjvf/j/fNTSKeMuLudL9rriRjJJV6Oh94bOMurLPZjxn2ynEZ1qHrCmy7+CWWFqB1CaWjpjxzA3y4XMd1T9YXH5BiOtCMyoSVCx3kh/kAB7wTm53mRb68UpUbm7To271AChPFXB3VDH48mw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
