appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Sy3RQH1vTCvdhMeAxtbvNKqKQtcDzQ1inrT9fLMnkdBaLDpIdbvoy+h5cq9AtUmgeZyugn5m/jQ5PtjGS68PNbugM9kTllyDt0C26mKAtjCO//dg1+yyUBFyFOyqO2dyzmxXRtXHaatLvfQrTIiksBOdC4OcKAf47MRMSes7RZhpcIoGE0011qtU8lxoSRPJkGk6FkF1zK3nrZUE50g6tW8QnDZjqbE2LZSZ3YY4VJSeSy7ViYCe5niP1qgfUL6fDRzAFEwhOoUxOHMP7M5Q8nFelGY3XoiGVfSnHPsTBjhLTYmu2GQEmrpWS3bbc3hAbY/KWtf1hRegLHTCXg36roW4zlnZFOm/7DILqNfWwAKGsX32x46bipF+FIsip4OBY7uQ/SjAugyUCtuNfBwhwr+X0vTdQXwzyDXoHginTie/eddqTNLd5+S6iXwSCRqdjxerE93NkrT8a+wewycdR1A9lqNGsxQXSOdbllaNuCqlUJZlGapC7nm343amCThv23yz/5hZuoLu9Fol8C09WvFu2I///iMaf/3f1cA0ca09FZrgMyeI9QVY0FMSoureeBuHvIs6m4W7tQ5xrVkLQxL6+0VIp1e12I6BHShRnGvYsqa4llmXMSGHYeVquGLEhhSFlFkn/R7DOWPbmXTZodpqSV578AGJtq8aLxojYd8=}
